### ISSUE TITLE
Running `grump <cmd>` twice runs the script twice

### ISSUE THREAD

**Issue by sunny-g** [grumpishmermaids/grump#27]
I installed [bettertabbing](https://github.com/mochuelo-kun/grump-bettertabbing) once, and thinking it wasn't working, ran `grump bettertabbing` again. After looking at the `.inputrc` it created, I saw that it had `echo`'ed the commands twice.

**Comment by keitharm** [comment]
Currently, the grump command defaults to installing and running the script on 1st run and only running the script for subsequent runs.

Maybe a "done" message at the end of bettertabbing (@mochuelo-kun) would help let the user know the installation was successful?

**Comment by mochuelo-kun** [comment]
Updated!
Thanks for the input, sunny!
